# Generated by Django 5.0.6 on 2024-07-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
